#!/usr/bin/env bash
# Materialize .env.local from the environment (Cloud Agent secrets are injected
# as env vars). Runs on each container start. Writes ONLY variables that are
# present, so it is safe when some integrations are not configured.
#
# Nothing here is secret: values come from the injected environment and land in
# .env.local, which is gitignored. Never commit .env.local.
set -euo pipefail

cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

ENV_FILE=".env.local"

# Convex's deploy key encodes the deployment name
# (e.g. "dev:frugal-dragon-943|..."), so derive CONVEX_URL/CONVEX_DEPLOYMENT
# when only CONVEX_DEPLOY_KEY was provided.
if [ -n "${CONVEX_DEPLOY_KEY:-}" ]; then
  dep="${CONVEX_DEPLOY_KEY%%|*}"   # dev:frugal-dragon-943
  name="${dep##*:}"                 # frugal-dragon-943
  : "${CONVEX_DEPLOYMENT:=$dep}"
  : "${CONVEX_URL:=https://${name}.convex.cloud}"
  export CONVEX_DEPLOYMENT CONVEX_URL
fi

# The live Inkbox webhook subscription is owned by the production Vercel host.
# Default these to that host so .env.local can never fall back to the
# `<handle>.inkboxwire.com` tunnel URL. A Cloud Agent has no inbound address, so
# `npm run webhooks` here must stay a no-op ("webhook exists") and must never
# re-point the subscription at this process — that would break the live Bro.
: "${INKBOX_WEBHOOK_URL:=https://bro-agent.vercel.app/webhooks/imessage}"
: "${EVE_URL:=https://bro-agent.vercel.app}"
export INKBOX_WEBHOOK_URL EVE_URL

# App-runtime + non-secret config the eve agent and scripts read.
VARS=(
  OPENROUTER_API_KEY AI_GATEWAY_API_KEY BRO_MODEL
  CONVEX_URL CONVEX_DEPLOYMENT CONVEX_DEPLOY_KEY BRO_INTERNAL_SECRET
  INKBOX_API_KEY INKBOX_WEBHOOK_SECRET INKBOX_AGENT_HANDLE INKBOX_WEBHOOK_URL ALLOWED_SENDERS
  COMPOSIO_API_KEY BROWSER_USE_API_KEY
  EVE_URL BRO_PUBLIC_URL BRO_IDENTITY_CAP BRO_PRICE_RUB
  YOOKASSA_SHOP_ID YOOKASSA_SECRET_KEY
)

tmp="$(mktemp)"
{
  echo "# Generated by .cursor/setup-env.sh on container start. Gitignored — do not commit."
  for v in "${VARS[@]}"; do
    if [ -n "${!v:-}" ]; then
      printf '%s=%s\n' "$v" "${!v}"
    fi
  done
} >"$tmp"
mv "$tmp" "$ENV_FILE"
chmod 600 "$ENV_FILE"

count="$(grep -c '=' "$ENV_FILE" || true)"
echo "setup-env: wrote $ENV_FILE ($count variables present)"

# Diagnostic: the model + Convex keys are the minimum for live agent turns.
# If they are missing, the panel Secrets were not injected into this VM — a real
# Cloud Agent (not a Task subagent / draft build) started after the secrets were
# saved to THIS environment should receive them.
if [ -z "${OPENROUTER_API_KEY:-}" ] || [ -z "${CONVEX_DEPLOY_KEY:-}" ]; then
  echo "setup-env: WARNING — OPENROUTER_API_KEY and/or CONVEX_DEPLOY_KEY not injected." >&2
  echo "setup-env: live agent turns need them. Check the Secrets panel (scope: Environment)." >&2
fi
